services:
  webProxy:
    image: traefik:v2.10
    command:
    #- "--api.insecure=false"
    - "--providers.docker"
    - "--providers.docker.exposedbydefault=false"
    - '--entryPoints.web.address=:${HTTP_PORT:-80}'
    - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    - '--entryPoints.websecure.address=:${HTTPS_PORT:-443}'
    - "--certificatesresolvers.leCerts.acme.tlschallenge=true"
    - '--certificatesresolvers.leCerts.acme.email=${CERT_MAIL}'
    - "--certificatesresolvers.leCerts.acme.storage=/letsencrypt/acme.json"
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
      #- 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webProxy

networks:
  webProxy:
    external: true
